"""empty message

Revision ID: 3d65c5d40f25
Revises: 0a7fd7dfe731
Create Date: 2017-08-07 17:35:06.798518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d65c5d40f25'
down_revision = '0a7fd7dfe731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    op.drop_column('users', 'device_id')
    # ### end Alembic commands ###
