"""empty message

Revision ID: 891fd177041d
Revises: 91ae0515bb3e
Create Date: 2017-08-08 00:18:27.005407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891fd177041d'
down_revision = '91ae0515bb3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
