"""empty message

Revision ID: 91ae0515bb3e
Revises: c314a03f4fcf
Create Date: 2017-08-08 00:09:26.902403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ae0515bb3e'
down_revision = 'c314a03f4fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('messages', 'message_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'id')
    # ### end Alembic commands ###
